### ISSUE TITLE
Compat MixedModels 4.0 MethodError: no method matching unscaledre!(::Vector{Float64}, ::ReMat{Float64, 2}, ::Matrix{Float64})

### ISSUE THREAD

**Issue by behinger** [palday/MixedModelsPermutations.jl#25]
I get the error ERROR: MethodError: no method matching unscaledre!(::Vector{Float64}, ::ReMat{Float64, 2}, ::Matrix{Float64}) when running permutation(10,m0) on a MixedModels4.0 model

**Comment by palday** [comment]
Yeah, that method has been renamed. I'm going to drop MixedModels 3.x compat to fix it.
