### ISSUE TITLE
Implementation Structure

### ISSUE THREAD

**Issue by behinger** [palday/MixedModelsPermutations.jl#5]
(not sure if this is helpful @palday will decide)

## Types

`MixedModelPermutation <: MixedModelFitCollection`

**Comment by palday** [comment]
We probably want something that parallels the structure of `MixedModelsBootstrap`. Maybe `MixedModelsPermutation` and ask MixedModels.jl to introduce an `AbstractMixedModelsFitCollection` or something. (cf. JuliaStats/MixedModels.jl#325).
